In [1]:
import numpy as np

In [2]:
myList = [1,2,3,4,5]
myList

[1, 2, 3, 4, 5]

In [3]:
myArray = np.array(myList)
myArray

array([1, 2, 3, 4, 5])

In [4]:
myTable = [[1,2,3],[4,5,6],[7,8,9]]

myMatrix = np.array(myTable)
myMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(2)

array([0.56671097, 0.06456625])

In [15]:
np.random.rand(5,5)

array([[0.08593878, 0.36354702, 0.71323203, 0.9223421 , 0.37694251],
       [0.96609391, 0.01740302, 0.90265859, 0.13626965, 0.85803268],
       [0.58928144, 0.77389851, 0.75742093, 0.65032589, 0.38804062],
       [0.67848809, 0.57873631, 0.783861  , 0.53096796, 0.59466494],
       [0.35960557, 0.47091103, 0.79526886, 0.32250652, 0.15449073]])

In [16]:
np.random.randint(1,10)

7

In [17]:
np.random.randint(1,100,5)

array([84, 39, 31, 83, 53])

In [18]:
np.random.seed(101)
np.random.rand(5)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698])

In [19]:
np.random.seed(101)
np.random.rand(5)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698])

In [20]:
a = np.arange(1,46)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [21]:
a.reshape(5,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [22]:
r = np.random.randint(0,100,10)
r

array([77, 40,  4, 63, 40, 60, 92, 64,  5, 12])

In [23]:
r.max()

92

In [24]:
r.argmax()

6

In [25]:
r.argmin()

2

In [26]:
# notice the two set of brackets
a.reshape(1,45)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [27]:
a.reshape(1,45).shape

(1, 45)

In [28]:
a.dtype

dtype('int64')

In [29]:
r = np.random.rand(5)
r

array([0.35213195, 0.1818924 , 0.78560176, 0.96548322, 0.23235366])

In [30]:
r.dtype

dtype('float64')