In [1]:
import numpy as np

In [2]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a[5]

5

In [4]:
a[4:7]

array([4, 5, 6])

In [5]:
a[0:5] = 10
a

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [6]:
# data is not copied!
s = a[0:6]
s

array([10, 10, 10, 10, 10,  5])

In [7]:
s[:] = 0
s

array([0, 0, 0, 0, 0, 0])

In [8]:
a

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [9]:
c = a.copy()
c

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [10]:
table = np.array(([1,2,3],[4,5,6],[7,8,9]))
table

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
table[0]

array([1, 2, 3])

In [12]:
table[0][1]

2

In [13]:
table[:2,1:]

array([[2, 3],
       [5, 6]])

In [14]:
table[2:]

array([[7, 8, 9]])

In [15]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [17]:
ba = a > 4

In [18]:
a[ba]

array([5, 6, 7, 8, 9])

In [19]:
a[a<2]

array([0, 1])