In [1]:
import numpy as np

In [2]:
a = np.arange(0,10)

In [3]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
a * a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
a / a

/tmp/ipykernel_43209/3063000341.py:1: RuntimeWarning: invalid value encountered in divide
  a / a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
1 / a

/tmp/ipykernel_43209/891846650.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [8]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
np.log(a)

/tmp/ipykernel_43209/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [12]:
a.sum()

45

In [13]:
a.mean()

4.5

In [14]:
a.max()

9

In [15]:
list = np.arange(1,17)
m = list.reshape(4,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
m.sum()

136

In [17]:
m.sum(axis=0)

array([28, 32, 36, 40])

In [18]:
m.sum(axis=1)

array([10, 26, 42, 58])